---
title: "MVA project"
author: "Lokesh Arora, Ankita Shinde"
date: "10/1/2020"
output:
  word_document: default
  pdf_document: default
github link: https://github.com/ankita1598/Walmart
---

```{r}
features = read.csv("D:/Ankita/SEMESTER 2/MVA/features.csv",header = T)
train = read.csv("D:/Ankita/SEMESTER 2/MVA/train.csv",header = T)
test = read.csv("D:/Ankita/SEMESTER 2/MVA/test.csv",header = T)
stores = read.csv("D:/Ankita/SEMESTER 2/MVA/stores.csv",header = T)

```
```{r}
dataset = merge(train,stores, by="Store")
```

```{r}
#dataset = merge(dataset,features, by="Store")

```
```{r}
library(lubridate)
dataset$year <- year(ymd(dataset$Date))
dataset$month <- month(ymd(dataset$Date)) 
dataset$day <- day(ymd(dataset$Date))
```
```{r}
library("plyr")
month_wise =ddply(dataset, .(month), summarize,  Sales=mean(Weekly_Sales))
barplot(month_wise$Sales, main="Monthly Sales", xlab="Month", ylab="Sales")
```

```{r}
store_wise =ddply(dataset, .(Store), summarize,  Sales=mean(Weekly_Sales))

barplot(store_wise$Sales, main="Store Sales", xlab="Stores", ylab="Sales", col = c('blue', 'red', 'green', 'pink', 'yellow'))
```
```{r}
dept_wise =ddply(dataset, .(Dept), summarize,  Sales=mean(Weekly_Sales))
barplot(dept_wise$Sales, main="Sales by Department", xlab="Departments", ylab="Sales")
```
```

```
```{r}
library("dplyr")
dept_sales =ddply(dataset, c("year","Dept"), summarize,  Sales=sum(Weekly_Sales))
top_depts = top_n(dept_sales, 30, Sales)
```
